[SIE-151] Reorganize experiment fields
neu-self-image-experiments/sie-firebase pull request #108
Opened 2021-04-21 08:01 UTC by fernandowinfield

### TLDR:
- Reorganized the fields of the Firestore **experiment** doc data model to be able to display more useful data in the Experiments page.
- Resolved pending TODOs in ExperimentsPage component.

*****

### In this PR:
- Updates to the experiment data model:
    - Removed fields:
        - admin
        - researcher
    - New fields:
        - creator
        - preSurvey
        - postSurvey
        - isOngoing

- Updates to Card component:
    - reduced most of the params of <Card/> into a new object param `experimentInfo`.
    - added new experiment info to be displayed when the ‘View details’ button is clicked (here’s where the researchers can access the link to our website that they can post in external platforms like SONA and mTurk).

- Updates to `getAllExperiments()` API:
    - Added the experiment doc ID to the response that’s returned so we can provide the link to researchers.

- Updates to AddExperiment component:
    - Added the new fields to the object that we post to Firestore.

- Updated to Experiments page:
    - Replaced the old auth with the new auth context
    - Fixed logic to filter ongoing vs inactive experiments

2021-04-21 08:10 UTC, fernandowinfield commented
@theodore3131, tagging you here just in case so you are aware of this change I made to the experiment doc data model

2021-04-21 18:00 UTC, stenizwahyudi commented on src/stories/pages/ExperimentsPage/ExperimentsPage.js
> +        body: exp.description.length > MAX_DESCRIPTION_LENGTH ?
I think let's just use 'body: exp.description' here. Trimming it doesn't seem to work well

2021-04-21 18:00 UTC, stenizwahyudi commented on src/stories/pages/ExperimentsPage/ExperimentsPage.js
>  const MAX_DESCRIPTION_LENGTH = 100;
Don't forget to delete this.

2021-04-21 18:00 UTC, stenizwahyudi commented on src/stories/pages/ExperimentsPage/ExperimentsPage.js
> -          body= {description.length > MAX_DESCRIPTION_LENGTH ?
This one too.

2021-04-21 18:02 UTC, stenizwahyudi commented on src/stories/pages/ExperimentsPage/ExperimentsPage.js
> +        body: exp.description.length > MAX_DESCRIPTION_LENGTH ?
Here too.

2021-04-21 18:05 UTC, stenizwahyudi commented on src/stories/components/Card/Card.js
> +      <p>Consent form Qualtrics survey:</p>
This is simply a styling preferences, but I'd say it's better to use <h5>Consent form Qualtrics survey:</h5>.
Similarly on line 47, 50, and 53.

2021-04-21 18:07 UTC, stenizwahyudi commented on src/stories/pages/ExperimentsPage/ExperimentsPage.js
>  // eslint-disable-next-line max-len
Don't forget to delete this.

2021-04-21 18:09 UTC, stenizwahyudi requested changes
Please add <h5>Pre-Survey Questionnaire to line 103 (I believe) on AddExperiment.js. Similarly to Post-Survey Questionnaire. I thought I made the changes already, but not sure why it's not showing.

2021-04-22 02:32 UTC, stenizwahyudi approved these changes

2021-04-22 02:36 UTC, merged