SIE-47 Added horizontal-title component
neu-self-image-experiments/sie-firebase pull request #7
Opened 2021-02-16 01:29 UTC by quanganhhoang

2021-02-16 01:34 UTC, quanganhhoang commented
Questions:
1.
> There should be a 50px gap between the title and paragraph; it could be decreased to 30px on tablets. Elements should be vertically stacked.

Is `50px` too big here? How would you prefer the padding/margin to be to display the gap?

2. Is `Work Sans` font installed yet?
3. Is there a template I should follow to add mobile responsive styling?

2021-02-16 20:17 UTC, alecherryy commented
> Questions:
> 1.
> 
> > There should be a 50px gap between the title and paragraph; it could be decreased to 30px on tablets. Elements should be vertically stacked.
> 
> Is `50px` too big here? How would you prefer the padding/margin to be to display the gap?
> 
>     1. Is `Work Sans` font installed yet?
> 
>     2. Is there a template I should follow to add mobile responsive styling?

@quanganhhoang re:50px, you can set the gap at 50px for large tablets and above, after that it can shrink to 30px.
1. Work sans is being imported in the `_font.scss`, just make sure your component's stylesheet is importing the 'variables.scss` file. 
2. There isn't hard rule for responsive behavior; use your best judgment based on what looks good.

2021-02-16 20:21 UTC, alecherryy commented on src/stories/components/HorizontalTitle/styles.scss
> +    margin-top: 0;
You don't need this. The `div` has no paddings nor margins by default

2021-02-16 20:40 UTC, alecherryy requested changes

2021-02-16 20:40 UTC, alecherryy commented on src/stories/components/HorizontalTitle/styles.scss
> +    &--medium {
Love this! Never used it this way myself.

2021-02-16 20:40 UTC, alecherryy commented on src/stories/components/HorizontalTitle/styles.scss
> +            font-size: 20px;
Font sizes are already declared in a global variables. Replace with `$font-size-lg`.

2021-02-16 20:40 UTC, alecherryy commented on src/stories/components/HorizontalTitle/styles.scss
> +        .horizontal-title__title {
`h1` font size should be the across across all component's instances. Remove this. What needs to change is the font size of the paragraph text.

2021-02-16 20:40 UTC, alecherryy commented on src/stories/components/HorizontalTitle/styles.scss
> +    font-size: 16px;
Remove this. Title does not change font size.

2021-02-16 20:40 UTC, alecherryy commented on src/stories/components/HorizontalTitle/styles.scss
> +    margin-bottom: 30px;
Use spacing global variable: `$spacing-1` and `$spacing-3`

2021-02-16 20:40 UTC, alecherryy commented on src/stories/components/HorizontalTitle/styles.scss
> +    margin: 0px;
1. Font family is being applied to `body` and is inherited by all of its children, so no need to declare it
2. Convert font-size to `rem` by doing `rem(13px)`
3. No need to declare margin and padding, the `div` has no padding nor margins by default

2021-02-16 20:40 UTC, alecherryy commented on src/stories/components/HorizontalTitle/styles.scss
> +}
No need to for this.

2021-02-16 20:40 UTC, alecherryy commented on src/stories/components/HorizontalTitle/HorizontalTitle.js
> +            <p className="horizontal-title__content">{content}</p>
Paragraphs shouldn't be nested inside of each other. Either convert this to a `div` or pass `{content}` as a string literal.

2021-02-16 20:40 UTC, alecherryy commented on src/stories/components/HorizontalTitle/HorizontalTitle.js
> +            {eyebrow ?
To get the horizontal layout, you'll probably want to put a wrapper `div` around the title and `eyebrow` and set the display of the component to grid or flex for large tablets and above. Example:

```
.horizontal-title {
        @include bp-tablet-lg {
            display: grid;
            grid-gap: $spacing-3;
        }

        @include bp-desktop {
            grid-gap: $spacing-5;
        }
    }
```

2021-02-17 00:37 UTC, quanganhhoang commented
Thanks for the detailed feedback! Much appreciate it! I addressed your comments @alecherryy

2021-02-17 22:59 UTC, alecherryy approved these changes

2021-02-17 23:01 UTC, merged