SIE127/128 fetch consent form result minor fix of get current user
neu-self-image-experiments/sie-firebase pull request #77
Opened 2021-04-01 18:12 UTC by bleachalon

**Summary:**
1. Created function to fetch stored Qualtrics data from Firestore.
2. Fixed the logic of getCurrentUser which caused infinite loading.

**Discussion**
There is one design uncertainty. Should I create one function to return all user-experiment data, or should I create different functions for each form (consent, post-survey, pre-survey)?

2021-04-01 18:25 UTC, quanganhhoang requested changes

2021-04-01 18:25 UTC, quanganhhoang commented on src/firebase/api/qualtrics.js
> +      data: snapshot.exists ? snapshot.data() : null,
1. Let's have a `const snapshotExists = snapshot.exists` so we don't have to call snapshot.exists multiple times. 
2. Typo at `sucesss` and let's use constants here

2021-04-01 18:25 UTC, quanganhhoang commented on src/firebase/api/users.js
> +      }
could you add a comment here explaining what this does?

2021-04-05 21:22 UTC, fernandowinfield commented
@bleachalon, sorry I was not aware of this PR. The frontend team preference is to have a separate function for each (consent, post-survey, pre-survey). Thanks!

2021-04-05 23:22 UTC, dustinlo approved these changes

2021-04-05 23:22 UTC, merged