Feature/sie 17 create grid layout
neu-self-image-experiments/sie-firebase pull request #9
Opened 2021-02-16 07:22 UTC by denglish7

Created grid layout

2021-02-16 21:25 UTC, alecherryy requested changes
@denglish7 I left a couple of small suggestions/changes; however, I noticed your grid is not responsive. You might want to double check that!

2021-02-16 21:25 UTC, alecherryy commented on src/stories/layouts/Grid/Grid.stories.js
> +            <h1>Test</h1>
I would updated the content of the sample grid item to be an `h3` and include a paragraph with sample content, like so:
```
<div className="grid__item">
    <h3>Test</h3>
    <p>Lorem ipsum dolor sit amet, aliquip pertinax intellegebat vel ad. 
    Quo diceret comprehensam id, mazim labore instructior et mea.</p>
</div>
```

2021-02-16 21:25 UTC, alecherryy commented on src/stories/layouts/Grid/styles.scss
> +}
Remove this. We don't want to make assumptions on the display of the grid items.

2021-02-16 21:25 UTC, alecherryy commented on src/stories/layouts/Grid/Grid.js
> +        <div className={['grid', `${numColumns}`].join(' ').trim()}>
I like the idea of using the number of columns; I would just update this to `grid--${numColumns}-col` and change the `numColumns` param to a number, which would return the following modifier class: `grid--3-col`.  That way we don't need to spell out numbers which is more likely to lead to typos and then bugs. Example of update:
```
const modifierClass = numColumns ? `grid--${numColumns}-col` : '';
    return (
        <div className={['grid', modifierClass].join(' ').trim()}>
            {children}
        </div>
    );
```

2021-02-16 21:25 UTC, alecherryy commented on src/stories/layouts/Grid/styles.scss
> +    @extend %shared;
You don't need this. Those styles are already present in the `.grid` class.

2021-02-18 02:01 UTC, denglish7 commented
> @denglish7 I left a couple of small suggestions/changes; however, I noticed your grid is not responsive. You might want to double check that!

2021-02-18 02:05 UTC, denglish7 commented
> > @denglish7 I left a couple of small suggestions/changes; however, I noticed your grid is not responsive. You might want to double check that!

Thank you! I have made the requested changes and the grid is now responsive with 1-4 columns

2021-02-18 18:42 UTC, alecherryy approved these changes

2021-02-18 18:44 UTC, merged